title: 前端代码规范
subtitle: "Front-End Coding Guidelines"
description: "Best Coding Guidelines For Front-End Developer."
author: FEMessage
language: zh-cn
timezone: UTC
url: http://levy9527.github.io/front-end-style-guide
root: /front-end-style-guide
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: https://github.com/levy9527/front-end-style-guide.git
  branch: gh-pages

disqus_shortname:
google_analytics: UA-4910098-10
baidu_analytics: bb4b770d7fdf4e05245cd1327199d813
fb_admins: 100000247608790
#swiftype_key: nxhXzi1rDss_9_P_6zBa
#twitter: o2circle
github: levy9527/front-end-style-guide
gh:
  user: levy9527
  repo: front-end-style-guide
